--- 
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=sunnydb
      - FF_APP_KEY=2AqnXujE5V92NPq5BOEG4BvLoPUjD2JG
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=America/New_York
      - APP_LOG_LEVEL=debug
    image: eds/fireflyiii_pi
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "4233:80"
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    environment: 
      - POSTGRES_PASSWORD=sunnydb
      - POSTGRES_USER=firefly_db
    image: "postgres:10"
    networks: 
      - firefly_iii_net
    ports:
      - "5432:5432"
    volumes: 
      - "firefly_iii_db:/var/lib/postgresql/data"
  backup:
    image: ubuntu
    volumes:
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
      - "firefly_iii_db:/var/lib/postgresql/data"
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
